language: node_js
sudo: false
node_js:
- "8"
- "9"
install:
- yarn install
- yarn add coveralls
script:
- npm run coverage
after_success:
- nyc report --reporter=text-lcov | coveralls
# cache:
#   directories:
#     - node_modules
